package com.rainier.pojo;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
@Entity
@Table(name="expert_video")
public class ExpertVideoDo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.id
     *
     * @mbggenerated
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.uuid
     *
     * @mbggenerated
     */
    @GeneratedValue(generator="UUID")
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.cover_img_url
     *
     * @mbggenerated
     */
    private String coverImgUrl;
    private String exportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.introduction
     *
     * @mbggenerated
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.file_url
     *
     * @mbggenerated
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.created
     *
     * @mbggenerated
     */
    private Timestamp created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.modified
     *
     * @mbggenerated
     */
    private Timestamp modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.modified_by
     *
     * @mbggenerated
     */
    private String modifiedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column expert_video.create_by
     *
     * @mbggenerated
     */
    private String createBy;
    private BigDecimal duration;
    private String type;

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public BigDecimal getDuration() {
        return duration;
    }

    public void setDuration(BigDecimal duration) {
        this.duration = duration;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table expert_video
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.id
     *
     * @return the value of expert_video.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.id
     *
     * @param id the value for expert_video.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.uuid
     *
     * @return the value of expert_video.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.uuid
     *
     * @param uuid the value for expert_video.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.title
     *
     * @return the value of expert_video.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.title
     *
     * @param title the value for expert_video.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.cover_img_url
     *
     * @return the value of expert_video.cover_img_url
     *
     * @mbggenerated
     */
    public String getCoverImgUrl() {
        return coverImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.cover_img_url
     *
     * @param coverImgUrl the value for expert_video.cover_img_url
     *
     * @mbggenerated
     */
    public void setCoverImgUrl(String coverImgUrl) {
        this.coverImgUrl = coverImgUrl == null ? null : coverImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.introduction
     *
     * @return the value of expert_video.introduction
     *
     * @mbggenerated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.introduction
     *
     * @param introduction the value for expert_video.introduction
     *
     * @mbggenerated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    public String getExportName() {
        return exportName;
    }

    public void setExportName(String exportName) {
        this.exportName = exportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.file_url
     *
     * @return the value of expert_video.file_url
     *
     * @mbggenerated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.file_url
     *
     * @param fileUrl the value for expert_video.file_url
     *
     * @mbggenerated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.created
     *
     * @return the value of expert_video.created
     *
     * @mbggenerated
     */
    public Timestamp getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.created
     *
     * @param created the value for expert_video.created
     *
     * @mbggenerated
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.modified
     *
     * @return the value of expert_video.modified
     *
     * @mbggenerated
     */
    public Timestamp getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.modified
     *
     * @param modified the value for expert_video.modified
     *
     * @mbggenerated
     */
    public void setModified(Timestamp modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.modified_by
     *
     * @return the value of expert_video.modified_by
     *
     * @mbggenerated
     */
    public String getModifiedBy() {
        return modifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.modified_by
     *
     * @param modifiedBy the value for expert_video.modified_by
     *
     * @mbggenerated
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy == null ? null : modifiedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column expert_video.create_by
     *
     * @return the value of expert_video.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column expert_video.create_by
     *
     * @param createBy the value for expert_video.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }
}